<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Referentiel extends \App\Entity\Referentiel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'presentation', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'programme', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'critereAdmission', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'critereEvaluation', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'promos', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'groupecompetence', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'briefs', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'statistiquesCompetences', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'competences'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'presentation', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'programme', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'critereAdmission', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'critereEvaluation', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'promos', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'groupecompetence', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'briefs', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'statistiquesCompetences', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Referentiel' . "\0" . 'competences'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Referentiel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle(string $libelle): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentation', []);

        return parent::getPresentation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentation(string $presentation): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentation', [$presentation]);

        return parent::setPresentation($presentation);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramme', []);

        return parent::getProgramme();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramme($programme): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramme', [$programme]);

        return parent::setProgramme($programme);
    }

    /**
     * {@inheritDoc}
     */
    public function getCritereAdmission(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCritereAdmission', []);

        return parent::getCritereAdmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setCritereAdmission(string $critereAdmission): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCritereAdmission', [$critereAdmission]);

        return parent::setCritereAdmission($critereAdmission);
    }

    /**
     * {@inheritDoc}
     */
    public function getCritereEvaluation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCritereEvaluation', []);

        return parent::getCritereEvaluation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCritereEvaluation(string $critereEvaluation): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCritereEvaluation', [$critereEvaluation]);

        return parent::setCritereEvaluation($critereEvaluation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromos', []);

        return parent::getPromos();
    }

    /**
     * {@inheritDoc}
     */
    public function addPromo(\App\Entity\Promo $promo): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPromo', [$promo]);

        return parent::addPromo($promo);
    }

    /**
     * {@inheritDoc}
     */
    public function removePromo(\App\Entity\Promo $promo): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePromo', [$promo]);

        return parent::removePromo($promo);
    }

    /**
     * {@inheritDoc}
     */
    public function getBriefs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBriefs', []);

        return parent::getBriefs();
    }

    /**
     * {@inheritDoc}
     */
    public function addBrief(\App\Entity\Brief $brief): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBrief', [$brief]);

        return parent::addBrief($brief);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBrief(\App\Entity\Brief $brief): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBrief', [$brief]);

        return parent::removeBrief($brief);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatistiquesCompetences(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatistiquesCompetences', []);

        return parent::getStatistiquesCompetences();
    }

    /**
     * {@inheritDoc}
     */
    public function addStatistiquesCompetence(\App\Entity\StatistiquesCompetences $statistiquesCompetence): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStatistiquesCompetence', [$statistiquesCompetence]);

        return parent::addStatistiquesCompetence($statistiquesCompetence);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStatistiquesCompetence(\App\Entity\StatistiquesCompetences $statistiquesCompetence): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStatistiquesCompetence', [$statistiquesCompetence]);

        return parent::removeStatistiquesCompetence($statistiquesCompetence);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(?string $statut): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMembers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMembers', []);

        return parent::removeMembers();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompetences(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompetences', []);

        return parent::getCompetences();
    }

    /**
     * {@inheritDoc}
     */
    public function addCompetence(\App\Entity\Competence $competence): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCompetence', [$competence]);

        return parent::addCompetence($competence);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCompetence(\App\Entity\Competence $competence): \App\Entity\Referentiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCompetence', [$competence]);

        return parent::removeCompetence($competence);
    }

}
