<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNgd5qd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNgd5qd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNgd5qd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNgd5qd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNNgd5qd\App_KernelDevDebugContainer([
    'container.build_hash' => 'NNgd5qd',
    'container.build_id' => '58fbb045',
    'container.build_time' => 1617215488,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNgd5qd');
