<?php

namespace ContainerSoKLUVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y6ZAStuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y6ZAStu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y6ZAStu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'grpcmpService' => ['privates', 'App\\Services\\GroupeCompetenceCompetenceServices', 'getGroupeCompetenceCompetenceServicesService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'validator' => ['services', 'validator', 'getValidatorService', false],
        ], [
            'grpcmpService' => 'App\\Services\\GroupeCompetenceCompetenceServices',
            'manager' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
