<?php

namespace ContainerSoKLUVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WKiN2S6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WKiN2S6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WKiN2S6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apprenant_repo' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
            'groupe_repo' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'apprenant_repo' => 'App\\Repository\\ApprenantRepository',
            'groupe_repo' => 'App\\Repository\\GroupeRepository',
            'manager' => '?',
        ]);
    }
}
