<?php

namespace ContainerSoKLUVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NELBMsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NEL_BMs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NEL_BMs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'app' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
            'grp' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
            'livrableattendu' => ['privates', 'App\\Repository\\LivrableAttenduRepository', 'getLivrableAttenduRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'validator' => ['services', 'validator', 'getValidatorService', false],
        ], [
            'app' => 'App\\Repository\\ApprenantRepository',
            'grp' => 'App\\Repository\\GroupeRepository',
            'livrableattendu' => 'App\\Repository\\LivrableAttenduRepository',
            'manager' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
