<?php

namespace ContainerSoKLUVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EEbOp_DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eEbOp.D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eEbOp.D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apprenant_repo' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
            'commentaire_repo' => ['privates', 'App\\Repository\\CommentaireGeneralRepository', 'getCommentaireGeneralRepositoryService', true],
            'promo_repo' => ['privates', 'App\\Repository\\PromoRepository', 'getPromoRepositoryService', true],
        ], [
            'apprenant_repo' => 'App\\Repository\\ApprenantRepository',
            'commentaire_repo' => 'App\\Repository\\CommentaireGeneralRepository',
            'promo_repo' => 'App\\Repository\\PromoRepository',
        ]);
    }
}
