<?php

namespace ContainerSoKLUVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataPersister1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\DataPersister1' shared autowired service.
     *
     * @return \App\DataPersister\DataPersister1
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataPersister/DataPersister1.php';

        return $container->privates['App\\DataPersister\\DataPersister1'] = new \App\DataPersister\DataPersister1(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
