<?php

namespace ContainerSoKLUVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_FixturesLoadCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine.fixtures_load_command' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/DependentFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/AppFixtures.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/FixtureGroupInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/GroupeFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/GroupeTagTagsFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ProfilFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ProfilSortieFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/PromoFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ReferentielFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/UserFixtures.php';

        $a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);

        $b = ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService'));

        $a->addFixtures([0 => ['fixture' => new \App\DataFixtures\AppFixtures($b), 'groups' => []], 1 => ['fixture' => new \App\DataFixtures\GroupeFixtures(), 'groups' => []], 2 => ['fixture' => new \App\DataFixtures\GroupeTagTagsFixtures(), 'groups' => []], 3 => ['fixture' => new \App\DataFixtures\ProfilFixtures(), 'groups' => []], 4 => ['fixture' => new \App\DataFixtures\ProfilSortieFixtures(), 'groups' => []], 5 => ['fixture' => new \App\DataFixtures\PromoFixtures(), 'groups' => []], 6 => ['fixture' => new \App\DataFixtures\ReferentielFixtures(), 'groups' => []], 7 => ['fixture' => new \App\DataFixtures\UserFixtures($b), 'groups' => []]]);

        $container->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setName('doctrine:fixtures:load');

        return $instance;
    }
}
